---
- name: Test K3s installation on master node
  hosts: master
  become: yes
  vars:
    domain_name: "{{ hostvars[inventory_hostname]['domain_name'] }}"
  tasks:
    - name: Install required packages
      apt:
        name:
          - software-properties-common
          - certbot
        state: present
        update_cache: yes
      check_mode: yes

    - name: Add Certbot PPA
      apt_repository:
        repo: ppa:certbot/certbot
      check_mode: yes

    - name: Install Certbot
      apt:
        name: certbot
        state: present
        update_cache: yes
      check_mode: yes

    - name: Simulate Let's Encrypt certificate generation
      command: echo "Simulating certificate generation for {{ domain_name }}"
      check_mode: yes

    - name: Simulate K3s installation on master
      command: echo "Simulating K3s installation on master"
      check_mode: yes

    - name: Simulate copying TLS certificates to K3s
      debug:
        msg: "Simulating copying TLS certificates for {{ domain_name }}"
      check_mode: yes

    - name: Simulate restarting K3s
      debug:
        msg: "Simulating K3s restart"
      check_mode: yes

- name: Test K3s installation on worker nodes
  hosts: worker
  become: yes
  tasks:
    - name: Simulate K3s installation on worker
      command: echo "Simulating K3s installation on worker"
      check_mode: yes

- name: Test K3s cluster verification
  hosts: master
  become: yes
  tasks:
    - name: Simulate waiting for nodes to be ready
      debug:
        msg: "Simulating waiting for nodes to be ready"
      check_mode: yes

    - name: Simulate displaying cluster info
      debug:
        msg: "Simulating cluster info display"
      check_mode: yes

- name: Test ArgoCD and Nginx Ingress deployment
  hosts: master
  become: yes
  vars:
    domain_name: "{{ hostvars[inventory_hostname]['domain_name'] }}"
  tasks:
    - name: Simulate copying ArgoCD manifest
      debug:
        msg: "Simulating copying ArgoCD manifest"
      check_mode: yes

    - name: Simulate deploying ArgoCD
      debug:
        msg: "Simulating ArgoCD deployment"
      check_mode: yes

    - name: Simulate copying Nginx Ingress manifest
      debug:
        msg: "Simulating copying Nginx Ingress manifest"
      check_mode: yes

    - name: Simulate deploying Nginx Ingress
      debug:
        msg: "Simulating Nginx Ingress deployment"
      check_mode: yes

    - name: Simulate waiting for ArgoCD to be ready
      debug:
        msg: "Simulating waiting for ArgoCD to be ready"
      check_mode: yes

    - name: Simulate getting ArgoCD admin password
      debug:
        msg: "Simulating retrieval of ArgoCD admin password"
      check_mode: yes

    - name: Display test completion message
      debug:
        msg: "K3s installation test completed successfully. ArgoCD would be accessible at https://{{ domain_name }}:84430"